USE [master]
GO

/****** Object:  Database [Customer]    Script Date: 16/09/2023 18:09:39 ******/
CREATE DATABASE [Customer]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Customer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Customer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Customer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Customer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Customer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Customer] SET ARITHABORT OFF 
GO

ALTER DATABASE [Customer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Customer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Customer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Customer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Customer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Customer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Customer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Customer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Customer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Customer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Customer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Customer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Customer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Customer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Customer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Customer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Customer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Customer] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Customer] SET  MULTI_USER 
GO

ALTER DATABASE [Customer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Customer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Customer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Customer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Customer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Customer] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Customer] SET  READ_WRITE 
GO

